name: Commit Watch

on:
  - pull_request

env:
  CI: 1
  ARTIFACT_DIR: ./artifacts

jobs:
  commit_watch:
    name: Run Commit Watch
    runs-on: ubuntu-18.04
    steps:
        - uses: actions/checkout@v2
          with:
            ref: ${{ github.event.pull_request.head.sha }}
            fetch-depth: 0
        - name: Commit Watch
          uses: tophat/commit-watch-action@v0.0.3
          with:
            github_token: ${{ secrets.GH_TOKEN }}
            artifact_dir: ${{ env.ARTIFACT_DIR }}
        - name: Upload Artifacts
          uses: actions/upload-artifact@v2
          with:
            name: commit-watch-artifacts
            path: ${{ env.ARTIFACT_DIR }}
